[greeter]
background=/usr/share/backgrounds/ktx-netlab/ktx-netlab-os.svg
theme-name=Adwaita
icon-theme-name=Adwaita
font-name=Sans 11
clock-format=%A, %d %B %Y  %H:%M
indicators=~host;~spacer;~clock;~spacer;~power
