backend = "xrender";
vsync = true;

shadow = true;
shadow-radius = 8;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.20;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 6;

inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;

corner-radius = 6;

blur-background = false;

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.95; };
  dock = { shadow = false; };
  dnd = { shadow = false; };
};
